version: "3"

services:
  rabbitmq:
    container_name: ajk_rabbitmq
    image: rabbitmq:3.7-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5672"]
      interval: 10s
      timeout: 10s
      retries: 3

  web:
    container_name: ajk_web
    image: alpine:3.8
    command: ["sh", "-c", "nc -z -v rabbitmq 5672"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    links:
      - rabbitmq
